services:
  backend:
    build: .
    ports:
      - 8080:8080
    environment:
      - DB_PASSWORD=1234
      - DB_USER=admin
      - DB_URL=jdbc:postgresql://db:5432/parking
    networks:
      - spring-postgres
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=parking
    volumes:
      - db-data-parking:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - spring-postgres

networks:
  spring-postgres:
volumes:
  db-data-parking: